# Generated by Django 5.1.4 on 2025-12-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
