# Generated by Django 5.1.4 on 2025-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Música', 'Música'), ('Xerrades', 'Xerrades'), ('Educació', 'Educació'), ('Esports', 'Esports'), ('Entreteniment', 'Entreteniment'), ('Tecnologia', 'Tecnologia'), ('Art i Creativitat', 'Art i Creativitat'), ('Altres', 'Altres')], max_length=50),
        ),
    ]
