# Generated by Django 3.2.25 on 2025-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Programat', 'Programat'), ('En Directe', 'En Directe'), ('Finalitzat', 'Finalitzat'), ('Cancel·lat', 'Cancel·lat')], default='Programat', max_length=20),
        ),
    ]
